# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-29 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsarh_app', '0002_auto_20190926_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delete',
            field=models.CharField(default='recieved', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='add', max_length=255),
            preserve_default=False,
        ),
    ]
