# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-29 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alsarh_app', '0003_auto_20190928_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delete',
            new_name='deletes',
        ),
    ]
