# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-20 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alsarh_app', '0004_auto_20190928_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orderHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistoryOrder', to='alsarh_app.Order')),
            ],
        ),
    ]
