# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('alsarh_app', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='userHistory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='HistoryUser', to='login_app.User'),
            preserve_default=False,
        ),
    ]
