# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsarh_app', '0007_auto_20191021_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='approved',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='completed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
