# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_delete'),
        ('alsarh_app', '0008_auto_20191021_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_to_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_message', to='alsarh_app.Order')),
                ('user_to_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_user', to='login_app.User')),
            ],
        ),
    ]
